### PR TITLE
fix: simplify.resolve detects reference loop and throws error

### LINKED ISSUE #2383: simplify.resolve blows up call stack in case of recursive references
Simplest example:
```
const expr = math.parse('a')
math.simplify.resolve(expr, {a:expr})
```

Silghtly more subtle:
```
const asubexpr = math.parse('a+1')
const bsubexpr = math.parse('b+2')
math.simplify.resolve(asubexpr, {a:bsubexpr, b:asubexpr})
```

Both calls throw  `RangeError: Maximum call stack size exceeded`.

It seems to me that any of the following would be more civilized behavior:

(a) Return the original expression unchanged.

(b) Only substitute a given variable once down any branch of the parse tree. In other words, the second snippet would return `a+1+2+1` in that it would substitute `b+2` into `a+1` to get `b+2+1`, and then substitute `a+1` into that to get `a+1+2+1` and then refuse to substitute `a` again because it had already substituted `a` farther up that branch of the parse tree.

(c) Detect such loops and throw a mathjs-specific error object with some diagnostic information (and not take the time to fill up the entire call stack).

With some guidance on which sort of resolution would be most in tune with mathjs architecture and that this seems worth fixing (it can be subtle in a complicated scope whether a reference loop has been created), I'd be happy to take a stab at a PR.

### PR DESCRIPTION
**Pull request by gwhitney**
Also adds reference documentation and embedded documentation for `simplify.resolve` (with docs for `simplify.simplifyCore` coming along for the ride). Making these additions involved extending both doc facilities to handle functions "one level down" from the top level, and to support descriptions of what errors a function might throw (which were already present in the reference docs for several other functions, and so will now be displayed).

Also extends `simplify.resolve` to perform variable substitution within _all_ node types (formerly it would be blocked by, e.g., an ArrayNode and not perform variable resolution within).

Adds tests for all new behaviors, including `simplify.resolve` throwing ReferenceErrors.

Resolves #2383.

### CODE REVIEW

File: src/function/algebra/simplify/resolve.js [hunk 1]
```diff
@@ -29,38 +31,59 @@ export const createResolve = /* #__PURE__ */ factory(name, dependencies, ({
...
+  function resolve (node, scope, within = []) { // note `within` not documented
+    // (since `within` is for internal cycle detection only).
     if (!scope) {
       return node
     }
     if (!isMap(scope)) {
       scope = createMap(scope)
     }
     if (isSymbolNode(node)) {
+      if (within.indexOf(node.name) !== -1) {
```
Comment (josdejong) [inline src/function/algebra/simplify/resolve.js:56]: Generally I prefer not to mutate function input arguments, but here with `within` (and only internally) it makes sense.

Would it make sense for performance to change make `within` a `Set` instead of an `Array`?

File: src/expression/embeddedDocs/function/algebra/simplify.js [hunk 2]
```diff
@@ -17,3 +17,39 @@ export const simplifyDocs = {
     'derivative', 'parse', 'evaluate'
```
Comment (josdejong) [inline src/expression/embeddedDocs/function/algebra/simplify.js:17]: Can you add refrences to `simplify.resolve` and `simplify.simplifyCore` in `simplify`?

File: tools/docgenerator.js [hunk 3]
```diff
@@ -453,6 +492,16 @@ function generateMarkdown (doc, functions) {
         '\n\n\n'
   }
 
+  if (doc.mayThrow) {
```
Comment (josdejong) [inline tools/docgenerator.js:495]: Nice improvements documenting the exceptions that a function may throw!

**Review by josdejong — CHANGES_REQUESTED** [review]
Really nice Job @gwhitney , thanks. I like that you took the time to improve on the automatically generated docs too.

I made a few minor inline remarks, and have one thought: shall we can flatten the function names `simplify.simplifyCore` and `simplify.resolve` into `simplifyCore` and `simplifyResolve`? So far the library doesn't have nested functions, and that is just of simple and straightforward :).

**Comment by gwhitney** [comment]
> I made a few minor inline remarks, and have one thought: shall we can flatten the function names `simplify.simplifyCore` and `simplify.resolve` into `simplifyCore` and `simplifyResolve`? So far the library doesn't have nested functions, and that is just of simple and straightforward :).

I think naming should be entirely at your judgment and I can see in this comment and elsewhere that you favor a single layer of public names in mathJS. So I will revert the portions of this that track documentation down to a second layer, and move these two functions to the top layer. As for their names there, I'd suggest simplifyCore and resolve; the latter has a clear meaning and purpose on its own, independent of simplify, and the name does not conflict.

File: src/function/algebra/simplify/resolve.js (hunk 1 above)
Comment (gwhitney) [reply src/function/algebra/simplify/resolve.js:56]: Ah I was not thinking of a case with 100s of variables, but I suppose someone may want to use mathjs for such a case. Will change.

File: src/expression/embeddedDocs/function/algebra/simplify.js (hunk 2 above)
Comment (gwhitney) [reply src/expression/embeddedDocs/function/algebra/simplify.js:17]: Will do, to their new top-level names.

**Comment by gwhitney** [comment]
OK, I think that should take care of all of the feedback. Thanks.

**Comment by josdejong** [comment]
Thanks

> As for their names there, I'd suggest simplifyCore and resolve

That sounds good 👍 . I do not see a conflict with some other function that we would want to call `resolve`.

**Comment by gwhitney** [comment]
Oh, I just realized that now that resolve and simplifyCore are at the top level, simplify should just register them as dependencies. Give me a minute and I will fix.

**Comment by gwhitney** [comment]
OK, that should do it, should be OK to merge now.

**Comment by gwhitney** [comment]
Oh and I have to do the same for rationalize, and then add the dependencies to factoriesNumber so the build won't fail. Now it should be OK to merge.

**Review by josdejong — APPROVED** [review]
Thanks, looks good!

**Comment by josdejong** [comment]
This is published now in `v10.2.0`. Thanks Glen!
